version: '3.8'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: 'Y'
    restart: unless-stopped
    networks:
      - myapp-network
  
  mssql:
    build:
      context: ./docker/mssql
      dockerfile: Dockerfile
    image: mssql-server
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Password!
      - ACCEPT_EULA=Y
    volumes:
      - "./docker/mssql/scripts/:/scripts:ro"
    networks:
      - myapp-network
  
networks:
  myapp-network:
    name: myapp-network
