@TaxCalculatorApi = http://localhost:5000

POST {{TaxCalculatorApi}}/api/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST {{TaxCalculatorApi}}/api/tax/calculate
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
  "postal_code": "7441",
  "annual_income": 2000
}

###

GET {{TaxCalculatorApi}}/api/tax/details
Authorization: Bearer {{BearerToken}}